production:
  # Uncomment the line with google_analytics_code and replace it with the code provided by Google Analytics. This
  # will turn on the analytics tracking.
  # google_analytics_code: UA-XXXXX-X
  
  # If you're using Flickr photosets, provide Flickr API key:
  # flickr_api_key: FLICKR-API-KEY
  
  # Mailer settings.
  mailer:
    from_name: From Name
    from_address: no-reply@example.com
    manager_locale: en
    
    # Set the delivery method for mailer. It will be used to set the ActionMailer::Base.delivery_method value.
    # delivery_method: smtp
    
    # If delivery method is set to smtp, set the SMTP server settings here. For example to use GMail, set it to smtp.gmail.com
    # smtp_settings:
      
      # If delivery method is set to smtp, set the SMTP server settings here. For example to use GMail, set it to smtp.gmail.com
      # address: smtp_address
    
      # SMTP server username. With GMail set it to your e-mail address
      # user_name: me@example.com
      
      # SMTP server password.
      # password: my_password
      
      # With Google Apps, set it to your domain name
      # domain: example.com
      
      # SMTP server port
      # port: 587
    
# Use the same configuration as in production. However, you should be use your own settings.
development:
  <<: *production

# Use the same configuration as in production. However, you should be use your own settings.
test:
  <<: *production